stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: pap-widget
    url: https://flowchart-lu.netlify.app
  only:
    - master
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod