/**
 * Localized labels for the options WebWriter renders in its sidebar.
 */
export const optionLabels = {
	/** "Font" */
	font: {
		en: "Font",
		ar: "الخط",
		bg: "Шрифт",
		cs: "Písmo",
		da: "Skrifttype",
		de: "Schriftart",
		el: "Γραμματοσειρά",
		es: "Fuente",
		et: "Font",
		fi: "Fontti",
		fr: "Police de caractères",
		hu: "Betűtípus",
		id: "Font",
		it: "Carattere",
		ja: "フォント",
		ko: "글꼴",
		lt: "Šriftas",
		lv: "Fonts",
		nb: "Skrifttype",
		nl: "Lettertype",
		pl: "Czcionka",
		"pt-BR": "Fonte",
		"pt-PT": "Tipo de letra",
		ro: "Font",
		ru: "Шрифт",
		sk: "Písmo",
		sl: "Pisava",
		sv: "Font",
		tr: "Yazı tipi",
		uk: "Шрифт",
		"zh-hans": "字体",
		"zh-hant": "字型",
	},

	/** "Font size" */
	fontSize: {
		en: "Font size",
		ar: "حجم الخط",
		bg: "Размер на шрифта",
		cs: "Velikost písma",
		da: "Skriftstørrelse",
		de: "Schriftgröße",
		el: "Μέγεθος γραμματοσειράς",
		es: "Tamaño de letra",
		et: "Kirjasuurus",
		fi: "Kirjasinkoko",
		fr: "Taille de la police",
		hu: "Betűméret",
		id: "Ukuran huruf",
		it: "Dimensione del carattere",
		ja: "フォントサイズ",
		ko: "글꼴 크기",
		lt: "Šrifto dydis",
		lv: "Fonta lielums",
		nb: "Skriftstørrelse",
		nl: "Lettergrootte",
		pl: "Rozmiar czcionki",
		"pt-BR": "Tamanho da fonte",
		"pt-PT": "Tamanho da letra",
		ro: "Dimensiunea fontului",
		ru: "Размер шрифта",
		sk: "Veľkosť písma",
		sl: "Velikost pisave",
		sv: "Fontstorlek",
		tr: "Yazı tipi boyutu",
		uk: "Розмір шрифту",
		"zh-hans": "字体大小",
		"zh-hant": "字型大小",
	},

	/** "Theme" */
	theme: {
		en: "Theme",
		ar: "الموضوع",
		bg: "Тема",
		cs: "Téma",
		da: "Tema",
		de: "Thema",
		el: "Θέμα",
		es: "Tema",
		et: "Teema",
		fi: "Teema",
		fr: "Thème",
		hu: "Téma",
		id: "Tema",
		it: "Tema",
		ja: "テーマだ",
		ko: "테마",
		lt: "Tema",
		lv: "Tēma",
		nb: "Tema",
		nl: "Thema",
		pl: "Temat",
		"pt-BR": "Tema",
		"pt-PT": "Tema",
		ro: "Tema",
		ru: "Тема",
		sk: "Téma",
		sl: "Tema",
		sv: "Tema",
		tr: "Tema",
		uk: "Тема",
		"zh-hans": "主题",
		"zh-hant": "主題",
	},

	/** "Zoom" */
	zoom: {
		en: "Zoom",
		ar: "زووم",
		bg: "Увеличаване",
		cs: "Přiblížení",
		da: "Zoom",
		de: "Zoom",
		el: "Ζουμ",
		es: "Zoom",
		et: "Suurendage",
		fi: "Zoomaa",
		fr: "Zoom",
		hu: "Nagyítás",
		id: "Zoom",
		it: "Zoom",
		ja: "ズーム",
		ko: "Zoom",
		lt: "Padidinti",
		lv: "Palielināt",
		nb: "Zoom",
		nl: "Zoom",
		pl: "Zoom",
		"pt-BR": "Zoom",
		"pt-PT": "Zoom",
		ro: "Zoom",
		ru: "Увеличить",
		sk: "Priblíženie",
		sl: "Povečanje",
		sv: "Zoom",
		tr: "Yakınlaştır",
		uk: "Збільшити",
		"zh-hans": "放大",
		"zh-hant": "放大",
	},

	/** "Disable student editing" */
	disableStudentEditing: {
		en: "Disable student editing",
		ar: "تعطيل تحرير الطلاب",
		bg: "Забрана за редактиране от ученици",
		cs: "Zakázat úpravy studenty",
		da: "Deaktiver elevredigering",
		de: "Bearbeitung für Lernende sperren",
		el: "Απενεργοποίηση επεξεργασίας μαθητών",
		es: "Desactivar edición del alumnado",
		et: "Keela õpilaste redigeerimine",
		fi: "Estä opiskelijoiden muokkaus",
		fr: "Désactiver l'édition des élèves",
		hu: "Tanulói szerkesztés letiltása",
		id: "Nonaktifkan pengeditan siswa",
		it: "Disattiva modifica studenti",
		ja: "学習者による編集を無効にする",
		ko: "학생 편집 비활성화",
		lt: "Išjungti mokinių redagavimą",
		lv: "Atspējot skolēnu rediģēšanu",
		nb: "Deaktiver elevredigering",
		nl: "Bewerken voor leerlingen uitzetten",
		pl: "Wyłącz edycję przez uczniów",
		"pt-BR": "Desativar edição pelos alunos",
		"pt-PT": "Desativar edição pelos alunos",
		ro: "Dezactivați editarea elevilor",
		ru: "Запретить редактирование ученикам",
		sk: "Zakázať úpravy študentmi",
		sl: "Onemogoči urejanje za učence",
		sv: "Inaktivera elevredigering",
		tr: "Öğrenci düzenlemesini kapat",
		uk: "Вимкнути редагування учнями",
		"zh-hans": "禁用学生编辑",
		"zh-hant": "停用學生編輯",
	},

	/** "Disable student panning" */
	disableStudentPanning: {
		en: "Disable student panning",
		ar: "تعطيل تحريك العرض للطلاب",
		bg: "Забрана за преместване на изгледа",
		cs: "Zakázat posun plátna studenty",
		da: "Deaktiver elevers panorering",
		de: "Ansicht für Lernende sperren",
		el: "Απενεργοποίηση μετακίνησης προβολής",
		es: "Desactivar desplazamiento del alumnado",
		et: "Keela õpilastel vaate liigutamine",
		fi: "Estä opiskelijoiden näkymän siirto",
		fr: "Désactiver le déplacement de la vue",
		hu: "Tanulói nézetmozgatás letiltása",
		id: "Nonaktifkan geser tampilan siswa",
		it: "Disattiva spostamento vista studenti",
		ja: "学習者による表示の移動を無効にする",
		ko: "학생 화면 이동 비활성화",
		lt: "Išjungti mokinių vaizdo slinkimą",
		lv: "Atspējot skolēnu skata pārvietošanu",
		nb: "Deaktiver elevers panorering",
		nl: "Verschuiven voor leerlingen uitzetten",
		pl: "Wyłącz przesuwanie przez uczniów",
		"pt-BR": "Desativar movimentação pelos alunos",
		"pt-PT": "Desativar deslocação pelos alunos",
		ro: "Dezactivați deplasarea vizualizării",
		ru: "Запретить перемещение вида ученикам",
		sk: "Zakázať posun plátna študentmi",
		sl: "Onemogoči premikanje pogleda",
		sv: "Inaktivera elevers panorering",
		tr: "Öğrenci kaydırmasını kapat",
		uk: "Вимкнути панорамування учнями",
		"zh-hans": "禁用学生平移画布",
		"zh-hant": "停用學生平移畫布",
	},

	/** "Standard" */
	themeStandard: {
		en: "Standard",
		ar: "قياسي",
		bg: "Стандартен",
		cs: "Standardní",
		da: "Standard",
		de: "Standard",
		el: "Πρότυπο",
		es: "Estándar",
		et: "Standard",
		fi: "Standardi",
		fr: "Standard",
		hu: "Standard",
		id: "Standar",
		it: "Standard",
		ja: "スタンダード",
		ko: "표준",
		lt: "Standartinis",
		lv: "Standarta",
		nb: "Standard",
		nl: "Standaard",
		pl: "Standard",
		"pt-BR": "Padrão",
		"pt-PT": "Padrão",
		ro: "Standard",
		ru: "Стандарт",
		sk: "Štandard",
		sl: "Standard",
		sv: "Standard",
		tr: "Standart",
		uk: "Стандартний",
		"zh-hans": "标准",
		"zh-hant": "標準",
	},

	/** "Pastel" */
	themePastel: {
		en: "Pastel",
		ar: "باستيل",
		bg: "Пастел",
		cs: "Pastel",
		da: "Pastel",
		de: "Pastell",
		el: "Παστέλ",
		es: "Pastel",
		et: "Pastell",
		fi: "Pastelli",
		fr: "Pastel",
		hu: "Pasztell",
		id: "Pastel",
		it: "Pastello",
		ja: "パステル",
		ko: "파스텔",
		lt: "Pastelė",
		lv: "Pastelis",
		nb: "Pastell",
		nl: "Pastel",
		pl: "Pastel",
		"pt-BR": "Pastel",
		"pt-PT": "Pastel",
		ro: "Pastel",
		ru: "Пастель",
		sk: "Pastel",
		sl: "Pastel",
		sv: "Pastell",
		tr: "Pastel",
		uk: "Пастель",
		"zh-hans": "粉彩",
		"zh-hant": "粉彩",
	},

	/** "Mono" */
	themeMono: {
		en: "Mono",
		ar: "أحادية",
		bg: "Mono",
		cs: "Mono",
		da: "Mono",
		de: "Mono",
		el: "Mono",
		es: "Mono",
		et: "Mono",
		fi: "Mono",
		fr: "Mono",
		hu: "Mono",
		id: "Mono",
		it: "Mono",
		ja: "モノ",
		ko: "Mono",
		lt: "Mono",
		lv: "Mono",
		nb: "Mono",
		nl: "Mono",
		pl: "Mono",
		"pt-BR": "Mono",
		"pt-PT": "Mono",
		ro: "Mono",
		ru: "Моно",
		sk: "Mono",
		sl: "Mono",
		sv: "Mono",
		tr: "Mono",
		uk: "Моно",
		"zh-hans": "单声道",
		"zh-hant": "單聲道",
	},

	/** "Black/White" */
	themeBlackWhite: {
		en: "Black/White",
		ar: "أسود/أبيض/أسود",
		bg: "Черно/бяло",
		cs: "Černá/bílá",
		da: "Sort/hvid",
		de: "Schwarz/Weiß",
		el: "Μαύρο/λευκό",
		es: "Negro/Blanco",
		et: "Must/valge",
		fi: "Musta/valkoinen",
		fr: "Noir/Blanc",
		hu: "Fekete/Fehér",
		id: "Hitam/Putih",
		it: "Nero/Bianco",
		ja: "ブラック/ホワイト",
		ko: "블랙/화이트",
		lt: "Juoda/balta",
		lv: "Melns/balts",
		nb: "Svart/hvit",
		nl: "Zwart/Wit",
		pl: "Czarny/Biały",
		"pt-BR": "Preto/branco",
		"pt-PT": "Preto/branco",
		ro: "Negru/alb",
		ru: "Черный/белый",
		sk: "Čierna/biela",
		sl: "Črna/bela",
		sv: "Svart/vit",
		tr: "Siyah/Beyaz",
		uk: "Чорно-білий",
		"zh-hans": "黑色/白色",
		"zh-hant": "黑色/白色",
	},
} satisfies Record<string, Record<string, string>>;
