/**
 * Localized labels for the options WebWriter renders in its sidebar.
 */
export const optionLabels = {
	/** "Font" */
	font: {
		en: "Font",
		ar: "الخط",
		bg: "Шрифт",
		cs: "Písmo",
		da: "Skrifttype",
		de: "Schriftart",
		el: "Γραμματοσειρά",
		es: "Fuente",
		et: "Font",
		fi: "Fontti",
		fr: "Police de caractères",
		hu: "Betűtípus",
		id: "Font",
		it: "Carattere",
		ja: "フォント",
		ko: "글꼴",
		lt: "Šriftas",
		lv: "Fonts",
		nb: "Skrifttype",
		nl: "Lettertype",
		pl: "Czcionka",
		"pt-BR": "Fonte",
		"pt-PT": "Tipo de letra",
		ro: "Font",
		ru: "Шрифт",
		sk: "Písmo",
		sl: "Pisava",
		sv: "Font",
		tr: "Yazı tipi",
		uk: "Шрифт",
		"zh-hans": "字体",
		"zh-hant": "字型",
	},

	/** "Font size" */
	fontSize: {
		en: "Font size",
		ar: "حجم الخط",
		bg: "Размер на шрифта",
		cs: "Velikost písma",
		da: "Skriftstørrelse",
		de: "Schriftgröße",
		el: "Μέγεθος γραμματοσειράς",
		es: "Tamaño de letra",
		et: "Kirjasuurus",
		fi: "Kirjasinkoko",
		fr: "Taille de la police",
		hu: "Betűméret",
		id: "Ukuran huruf",
		it: "Dimensione del carattere",
		ja: "フォントサイズ",
		ko: "글꼴 크기",
		lt: "Šrifto dydis",
		lv: "Fonta lielums",
		nb: "Skriftstørrelse",
		nl: "Lettergrootte",
		pl: "Rozmiar czcionki",
		"pt-BR": "Tamanho da fonte",
		"pt-PT": "Tamanho da letra",
		ro: "Dimensiunea fontului",
		ru: "Размер шрифта",
		sk: "Veľkosť písma",
		sl: "Velikost pisave",
		sv: "Fontstorlek",
		tr: "Yazı tipi boyutu",
		uk: "Розмір шрифту",
		"zh-hans": "字体大小",
		"zh-hant": "字型大小",
	},

	/** "Theme" */
	theme: {
		en: "Theme",
		ar: "الموضوع",
		bg: "Тема",
		cs: "Téma",
		da: "Tema",
		de: "Thema",
		el: "Θέμα",
		es: "Tema",
		et: "Teema",
		fi: "Teema",
		fr: "Thème",
		hu: "Téma",
		id: "Tema",
		it: "Tema",
		ja: "テーマだ",
		ko: "테마",
		lt: "Tema",
		lv: "Tēma",
		nb: "Tema",
		nl: "Thema",
		pl: "Temat",
		"pt-BR": "Tema",
		"pt-PT": "Tema",
		ro: "Tema",
		ru: "Тема",
		sk: "Téma",
		sl: "Tema",
		sv: "Tema",
		tr: "Tema",
		uk: "Тема",
		"zh-hans": "主题",
		"zh-hant": "主題",
	},

	/** "Zoom" */
	zoom: {
		en: "Zoom",
		ar: "زووم",
		bg: "Увеличаване",
		cs: "Přiblížení",
		da: "Zoom",
		de: "Zoom",
		el: "Ζουμ",
		es: "Zoom",
		et: "Suurendage",
		fi: "Zoomaa",
		fr: "Zoom",
		hu: "Nagyítás",
		id: "Zoom",
		it: "Zoom",
		ja: "ズーム",
		ko: "Zoom",
		lt: "Padidinti",
		lv: "Palielināt",
		nb: "Zoom",
		nl: "Zoom",
		pl: "Zoom",
		"pt-BR": "Zoom",
		"pt-PT": "Zoom",
		ro: "Zoom",
		ru: "Увеличить",
		sk: "Priblíženie",
		sl: "Povečanje",
		sv: "Zoom",
		tr: "Yakınlaştır",
		uk: "Збільшити",
		"zh-hans": "放大",
		"zh-hant": "放大",
	},

	/** "Allow editing" */
	allowEditing: {
		en: "Allow editing",
		ar: "السماح بالتحرير",
		bg: "Разрешаване на редактирането",
		cs: "Povolit úpravy",
		da: "Tillad redigering",
		de: "Bearbeitung zulassen",
		el: "Επιτρέψτε την επεξεργασία",
		es: "Permitir la edición",
		et: "Lubage redigeerimine",
		fi: "Salli muokkaus",
		fr: "Autoriser l'édition",
		hu: "Szerkesztés engedélyezése",
		id: "Izinkan pengeditan",
		it: "Consentire la modifica",
		ja: "編集を許可する",
		ko: "편집을 허용합니다",
		lt: "Leisti redaguoti",
		lv: "Atļaut rediģēšanu",
		nb: "Tillat redigering",
		nl: "Bewerken toestaan",
		pl: "Zezwalaj na edycję",
		"pt-BR": "Permitir edição",
		"pt-PT": "Permitir a edição",
		ro: "Permiteți editarea",
		ru: "Разрешить редактирование",
		sk: "Povolenie úprav",
		sl: "Omogočite urejanje",
		sv: "Tillåt redigering",
		tr: "Düzenlemeye izin verin",
		uk: "Дозволити редагування",
		"zh-hans": "允许编辑",
		"zh-hant": "允許編輯",
	},

	/** "Allow moving" */
	allowMoving: {
		en: "Allow moving",
		ar: "السماح بالتحرك",
		bg: "Разрешете преместването",
		cs: "Povolit stěhování",
		da: "Tillad at flytte",
		de: "Bewegung zulassen",
		el: "Επιτρέψτε τη μετακίνηση",
		es: "Permitir la mudanza",
		et: "Lubage liikumine",
		fi: "Salli liikkuminen",
		fr: "Permettre le déplacement",
		hu: "Engedélyezze a mozgást",
		id: "Biarkan bergerak",
		it: "Consentire lo spostamento",
		ja: "移動を許可する",
		ko: "이동을 허용합니다",
		lt: "Leiskite judėti",
		lv: "Ļaujiet pārvietoties",
		nb: "Tillat flytting",
		nl: "Verplaatsen toestaan",
		pl: "Zezwalaj na poruszanie się",
		"pt-BR": "Permitir a movimentação",
		"pt-PT": "Permitir a deslocação",
		ro: "Permiteți deplasarea",
		ru: "Разрешите переезд",
		sk: "Povoľte pohyb",
		sl: "Omogočite premikanje",
		sv: "Tillåt rörelse",
		tr: "Taşınmaya izin verin",
		uk: "Дозвольте рухатися",
		"zh-hans": "允许移动",
		"zh-hant": "允許移動",
	},

	/** "Standard" */
	themeStandard: {
		en: "Standard",
		ar: "قياسي",
		bg: "Стандартен",
		cs: "Standardní",
		da: "Standard",
		de: "Standard",
		el: "Πρότυπο",
		es: "Estándar",
		et: "Standard",
		fi: "Standardi",
		fr: "Standard",
		hu: "Standard",
		id: "Standar",
		it: "Standard",
		ja: "スタンダード",
		ko: "표준",
		lt: "Standartinis",
		lv: "Standarta",
		nb: "Standard",
		nl: "Standaard",
		pl: "Standard",
		"pt-BR": "Padrão",
		"pt-PT": "Padrão",
		ro: "Standard",
		ru: "Стандарт",
		sk: "Štandard",
		sl: "Standard",
		sv: "Standard",
		tr: "Standart",
		uk: "Стандартний",
		"zh-hans": "标准",
		"zh-hant": "標準",
	},

	/** "Pastel" */
	themePastel: {
		en: "Pastel",
		ar: "باستيل",
		bg: "Пастел",
		cs: "Pastel",
		da: "Pastel",
		de: "Pastell",
		el: "Παστέλ",
		es: "Pastel",
		et: "Pastell",
		fi: "Pastelli",
		fr: "Pastel",
		hu: "Pasztell",
		id: "Pastel",
		it: "Pastello",
		ja: "パステル",
		ko: "파스텔",
		lt: "Pastelė",
		lv: "Pastelis",
		nb: "Pastell",
		nl: "Pastel",
		pl: "Pastel",
		"pt-BR": "Pastel",
		"pt-PT": "Pastel",
		ro: "Pastel",
		ru: "Пастель",
		sk: "Pastel",
		sl: "Pastel",
		sv: "Pastell",
		tr: "Pastel",
		uk: "Пастель",
		"zh-hans": "粉彩",
		"zh-hant": "粉彩",
	},

	/** "Mono" */
	themeMono: {
		en: "Mono",
		ar: "أحادية",
		bg: "Mono",
		cs: "Mono",
		da: "Mono",
		de: "Mono",
		el: "Mono",
		es: "Mono",
		et: "Mono",
		fi: "Mono",
		fr: "Mono",
		hu: "Mono",
		id: "Mono",
		it: "Mono",
		ja: "モノ",
		ko: "Mono",
		lt: "Mono",
		lv: "Mono",
		nb: "Mono",
		nl: "Mono",
		pl: "Mono",
		"pt-BR": "Mono",
		"pt-PT": "Mono",
		ro: "Mono",
		ru: "Моно",
		sk: "Mono",
		sl: "Mono",
		sv: "Mono",
		tr: "Mono",
		uk: "Моно",
		"zh-hans": "单声道",
		"zh-hant": "單聲道",
	},

	/** "Black/White" */
	themeBlackWhite: {
		en: "Black/White",
		ar: "أسود/أبيض/أسود",
		bg: "Черно/бяло",
		cs: "Černá/bílá",
		da: "Sort/hvid",
		de: "Schwarz/Weiß",
		el: "Μαύρο/λευκό",
		es: "Negro/Blanco",
		et: "Must/valge",
		fi: "Musta/valkoinen",
		fr: "Noir/Blanc",
		hu: "Fekete/Fehér",
		id: "Hitam/Putih",
		it: "Nero/Bianco",
		ja: "ブラック/ホワイト",
		ko: "블랙/화이트",
		lt: "Juoda/balta",
		lv: "Melns/balts",
		nb: "Svart/hvit",
		nl: "Zwart/Wit",
		pl: "Czarny/Biały",
		"pt-BR": "Preto/branco",
		"pt-PT": "Preto/branco",
		ro: "Negru/alb",
		ru: "Черный/белый",
		sk: "Čierna/biela",
		sl: "Črna/bela",
		sv: "Svart/vit",
		tr: "Siyah/Beyaz",
		uk: "Чорно-білий",
		"zh-hans": "黑色/白色",
		"zh-hant": "黑色/白色",
	},
} satisfies Record<string, Record<string, string>>;
